
server:
  #https端口号.
  port: 8080
  servlet:
    context-path: /
#  ssl:
#    #证书的路径.
#    key-store: classpath:keystore.p12
#    #证书密码
#    key-store-password: centennial
#    #秘钥库类型
#    keyStoreType: PKCS12
#    #证书别名
#    keyAlias: tomcat


spring:
  mail:
    host: smtp.gmail.com
    username: geshi6746@gmail.com
    password: wjrdtaeoubgpaabp
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465
    properties.mail.display.sendmail: Javen
    properties.mail.display.sendname: Spring Boot Guide Email
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    from: geshi6746@gmail.com
    default-encoding: utf-8
  datasource:
    url: jdbc:sqlite:/Users/wylllll/Desktop/Agency.db
    # url: jdbc:sqlite:C:/Users/dell/Downloads/Agency.db
    # url: jdbc:sqlite:C:/Users/wei5927/Desktop/Agency.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
  jackson:
    time-zone: GMT-5